# Site settings
title: Henry Laynesa Jr
description: Data Science Enthusiast
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Henry Laynesa Jr
user_description: I am a Bachelor of Science in Computer Science fresh graduate from University of the Philippines Diliman looking to start a career in Data Science where I can apply my technical expertise in machine learning to create high-impact for social good.
user_title: Data Science Enthusiast
email: henry.laynesa@gmail.com
# twitter_username: lorem_ipsum
github_username:  henrylaynesa
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
